name: Postman API Tests

on:
  push:
    branches: [ github-actions ]

jobs:
  postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Postman Tests
        run: |
          mkdir -p reports
          newman run collections/api-ci-project-collection.json \
            -e environments/environments-test.json \
            -r cli,htmlextra \
            --reporter-htmlextra-export reports/report.html

      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: reports/report.html